//NEXTJS
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//STYLES
import "../styles/index.css";


const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'NextJS App',
  description: 'Generated by NextJS'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}