import type { Metadata } from "next";
import { Inter } from "next/font/google";
//STYLES
import "../styles/index.css";
import Layout from "../components/layouts/Layout";
import { Provider } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QuickdropX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <Layout> {children} </Layout>
        </Provider>
      </body>
    </html>
  );
}